// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Block: typeof import('./src/components/anchor/Block.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    Game: typeof import('./src/components/anchor/Game.vue')['default']
    GamePlate: typeof import('./src/components/anchor/GamePlate.vue')['default']
    Header: typeof import('./src/components/anchor/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftPanel: typeof import('./src/components/anchor/LeftPanel.vue')['default']
    Plate: typeof import('./src/components/anchor/Plate.vue')['default']
    Timer: typeof import('./src/components/anchor/Timer.vue')['default']
  }
}

export { }
