// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Block: typeof import('./src/components/anchor/Block.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Game: typeof import('./src/components/anchor/Game.vue')['default']
    GamePlate: typeof import('./src/components/anchor/GamePlate.vue')['default']
    Header: typeof import('./src/components/anchor/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftPanel: typeof import('./src/components/anchor/LeftPanel.vue')['default']
    Login: typeof import('./src/components/backend/Login.vue')['default']
    Plate: typeof import('./src/components/anchor/Plate.vue')['default']
    Timer: typeof import('./src/components/anchor/Timer.vue')['default']
    UserList: typeof import('./src/components/backend/UserList.vue')['default']
    WorkStation: typeof import('./src/components/backend/WorkStation.vue')['default']
    WorkTabs: typeof import('./src/components/backend/WorkTabs.vue')['default']
  }
}

export { }
